name: Update Strava data
on:
  schedule:
    - cron: '0 * * * *'          # elk uur
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # ▸ Maak alle benodigde secrets beschikbaar als env-vars
    env:
      USERS: ${{ secrets.USERS }}

      # ---- USER 1 ----
      LEANDER_CLIENT_ID:      ${{ secrets.LEANDER_CLIENT_ID }}
      LEANDER_CLIENT_SECRET:  ${{ secrets.LEANDER_CLIENT_SECRET }}
      LEANDER_REFRESH_TOKEN:  ${{ secrets.LEANDER_REFRESH_TOKEN }}

      # ---- USER 2 ----
      STRAVA_CLIENT_ID:     ${{ secrets.STRAVA_CLIENT_ID }}
      STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
      STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}

      # ▸ voeg hier meer users toe als je ze in USERS zet

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install node-fetch@2

      - name: Run Strava export
        run: node scripts/update-strava.js

      - name: Ensure .nojekyll present
        run: |
          test -f .nojekyll || touch .nojekyll
          git add .nojekyll

      - name: Commit output
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "GitHub Actions"
          git add data                  # <- pakt nu ook alle submappen
          git commit -m "chore: auto-update Strava data" || echo "No changes"
          git push