name: Update Strava data
on:
  schedule:
    # elke 30 minuten van 04:00 t/m 20:30 UTC
    - cron: '*/30 7-20 * * *'
  workflow_dispatch:

concurrency:
  group: strava-update
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    # ▸ Maak alle benodigde secrets beschikbaar als env-vars
    env:
      USERS: ${{ secrets.USERS }}

      # ---- USER 1 ----
      LEANDER_CLIENT_ID:      ${{ secrets.LEANDER_CLIENT_ID }}
      LEANDER_CLIENT_SECRET:  ${{ secrets.LEANDER_CLIENT_SECRET }}
      LEANDER_REFRESH_TOKEN:  ${{ secrets.LEANDER_REFRESH_TOKEN }}

      # ---- USER 2 ----
      JENNA_CLIENT_ID:     ${{ secrets.JENNA_CLIENT_ID }}
      JENNA_CLIENT_SECRET: ${{ secrets.JENNA_CLIENT_SECRET }}
      JENNA_REFRESH_TOKEN: ${{ secrets.JENNA_REFRESH_TOKEN }}

      # ▸ voeg hier meer users toe als je ze in USERS zet

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install node-fetch@2

      - name: Run Strava export
        run: node scripts/update-strava.js

      - name: Ensure .nojekyll present
        run: |
          test -f .nojekyll || touch .nojekyll
          git add .nojekyll

      - name: Commit output
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "GitHub Actions"
          git add data                  # <- pakt nu ook alle submappen
          git commit -m "chore: auto-update Strava data" || echo "No changes"
          git push